# GitHub Sponsors & Funding Configuration
# Baker Street Laboratory - AI Research Framework

# GitHub Sponsors
github: BoozeLee

# Patreon
patreon: boozelee

# Ko-fi
ko_fi: boozelee

# Open Collective
# open_collective: baker-street-laboratory

# Tidelift
# tidelift: npm/baker-street-laboratory

# Community Bridge
# community_bridge: baker-street-laboratory

# Liberapay
# liberapay: boozelee

# IssueHunt
# issuehunt: BoozeLee

# Other funding sources
custom: ['https://paypal.me/boozelee', 'https://buymeacoffee.com/boozelee']
