name: Automated Research Pipeline

on:
  schedule:
    # Run weekly research updates (Sundays at 2 AM UTC)
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      research_query:
        description: 'Research query to execute'
        required: true
        default: 'Latest developments in AI research'
      output_branch:
        description: 'Branch to commit results to'
        required: false
        default: 'automated-research'

jobs:
  automated-research:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor || github.event_name == 'schedule'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create output branch
      run: |
        BRANCH_NAME="${{ github.event.inputs.output_branch || 'automated-research' }}"
        git checkout -b "$BRANCH_NAME-$(date +%Y%m%d)" || git checkout "$BRANCH_NAME-$(date +%Y%m%d)"
    
    - name: Run research pipeline
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        BING_API_KEY: ${{ secrets.BING_API_KEY }}
      run: |
        QUERY="${{ github.event.inputs.research_query || 'Weekly AI research trends and developments' }}"
        echo "🔬 Running automated research: $QUERY"
        
        # Create timestamped research directory
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        OUTPUT_DIR="research/automated_runs/$TIMESTAMP"
        mkdir -p "$OUTPUT_DIR"
        
        # Run the research pipeline
        python implementation/src/main.py \
          --mode research \
          --query "$QUERY" \
          --output-dir "$OUTPUT_DIR" \
          --log-level INFO
    
    - name: Generate research summary
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        OUTPUT_DIR="research/automated_runs/$TIMESTAMP"
        
        # Create a summary file
        cat > "$OUTPUT_DIR/README.md" << EOF
        # Automated Research Run - $TIMESTAMP
        
        **Query:** ${{ github.event.inputs.research_query || 'Weekly AI research trends and developments' }}
        **Executed:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        **Triggered by:** ${{ github.event_name }}
        **Repository:** ${{ github.repository }}
        **Commit:** ${{ github.sha }}
        
        ## Results
        
        This directory contains the automated research results generated by the Baker Street Laboratory pipeline.
        
        ## Files Generated
        
        $(find "$OUTPUT_DIR" -type f -name "*.md" -o -name "*.json" -o -name "*.txt" | sed 's|^|* |')
        
        ## Next Steps
        
        1. Review the generated research findings
        2. Validate key insights and sources
        3. Consider integrating findings into main research documentation
        4. Update agent configurations if needed
        
        ---
        *Generated automatically by Baker Street Laboratory*
        EOF
    
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        git add research/automated_runs/$TIMESTAMP/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Automated research run: $TIMESTAMP
          
          Query: ${{ github.event.inputs.research_query || 'Weekly AI research trends' }}
          Triggered: ${{ github.event_name }}
          
          This commit contains automatically generated research findings.
          Please review before merging into main branch."
          
          # Push to the branch
          BRANCH_NAME="${{ github.event.inputs.output_branch || 'automated-research' }}-$(date +%Y%m%d)"
          git push origin "$BRANCH_NAME"
          
          echo "✅ Results committed to branch: $BRANCH_NAME"
        fi
    
    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.event.inputs.output_branch || 'automated-research' }}-$(date +%Y%m%d)
        title: "🤖 Automated Research Results - $(date +%Y-%m-%d)"
        body: |
          ## Automated Research Results
          
          **Query:** ${{ github.event.inputs.research_query || 'Weekly AI research trends and developments' }}
          **Execution Time:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          **Trigger:** ${{ github.event_name }}
          
          This PR contains automatically generated research findings from the Baker Street Laboratory pipeline.
          
          ### What's Included
          - Research analysis and findings
          - Source citations and references  
          - Generated insights and summaries
          - Metadata and execution logs
          
          ### Review Checklist
          - [ ] Validate key research findings
          - [ ] Check source credibility and citations
          - [ ] Review generated insights for accuracy
          - [ ] Consider integration with existing research
          - [ ] Update documentation if needed
          
          ### Next Steps
          After review and approval:
          1. Merge this PR to integrate findings
          2. Update main research documentation
          3. Consider agent configuration improvements
          
          ---
          *This PR was created automatically by the Baker Street Laboratory research pipeline.*
        labels: |
          automated
          research
          needs-review
